Traceback (most recent call last):
  File "bert_MaskedLM_CL.py", line 41, in <module>
    from lib import subTrainer, FoolDataCollatorForSeq2Seq 
  File "/remote-home/xtzhang/CTC/CTC2021/SpecialEdition/lib.py", line 138, in <module>
    @dataclass
NameError: name 'dataclass' is not defined
